contact_links:
  - name: Question
    url: https://github.com/bevyengine/atomicow/discussions
    about: Questions about how to use or contribute belong in Github Discussions.
      You can use the search to check if someone already answered your question!

  - name: Community
    url: https://discord.gg/bevy
    about: If you'd like to converse with members of the `bevyengine` community, join us on discord. There is a channel for development of this crate.
